version: '2'
services:
  eurekaserver:
    image:   oselesley/tmx_eurekasvr:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
  configserver:
    image: oselesley/tmx_confsvr:0.0.1-SNAPSHOT
    ports:
      - "8888:8888"
    environment:
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY:       "IMSYMMETRIC"

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres_dev"
      POSTGRES_PASSWORD: "postgr@s_dev"
      POSTGRES_DB: "eagle_eye_dev"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql

  licensing_service:
    image: oselesley/tmx_licensing-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      PROFILE: dev
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      CONFIGSERVER_PORT: 8888
      EUREKASERVER_PORT:   "8761"
      DATABASESERVER_PORT: 5432
      ENCRYPT_KEY: "IMSYMMETRIC"
    depends_on:
      - database
  organization_service:
    image: oselesley/tmx_organization-service:0.0.1-SNAPSHOT
    ports:
      - "8085:8085"
    environment:
      PROFILE: "dev"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:      "IMSYMMETRIC"
    depends_on:
      - database

