tracer:
  property: I AM THE DEFAULT

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://database:5432/eagle_eye_local
    platform: postgres
    username: postgres
    password: postgr@s
    driverClassName: org.postgresql.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1