server:
  port: 8888


#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
##          search-locations: file:///usr/local/configserver/src/main/resources/config/licensingservice,
##            file:///usr/local/configserver/BOOT-INF/classes/config/licensingservice
#          searchLocations: classpath:config/,classpath:config/licensingservice
spring:
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/oselesley/config-repo
          search-paths: licensingservice,organizationservice
        encrypt:
          enabled: false
      discovery:
        enabled: true

